package cli

import (
	"github.com/spf13/cobra"
)

func registerRootFlags(cmd *cobra.Command, opts *rootOptions) {
	cmd.Flags().StringVarP(&opts.Request.Model, "model", "m", "", "The model to use")
	cmd.Flags().StringVar(&opts.Request.Provider, "provider", "", "Provider to use: openai, anthropic, gemini, or ollama")
	cmd.Flags().StringVarP(&opts.Request.System, "system", "S", "", "A system prompt to prepend")
	cmd.Flags().StringSliceVar(&opts.Request.Fragments, "fragment", nil, "Append named fragments to the prompt")
	cmd.Flags().BoolVarP(&opts.Request.AnalyzeLogs, "analyze-logs", "a", false, "Analyze log input with a log-focused system prompt")
	cmd.Flags().StringVar(&opts.Request.StdinMode, "stdin-mode", "auto", "How to combine piped stdin with the prompt: auto, append, or replace")
	cmd.Flags().StringVar(&opts.Request.StdinLabel, "stdin-label", "input", "Label to use when composing piped stdin into the prompt")
	cmd.Flags().StringSliceVar(&opts.Request.Transforms, "transform", nil, "Apply a named ingest transform to piped stdin")
	cmd.Flags().BoolVar(&opts.Request.NoPipeline, "no-pipeline", false, "Disable any selected or configured log profile/pipeline")
	cmd.Flags().BoolVar(&opts.Request.Clean, "clean", false, "Apply common log sanitizers before reduction")
	cmd.Flags().BoolVar(&opts.Request.Dedupe, "dedupe", false, "Apply exact log-line deduplication")
	cmd.Flags().BoolVar(&opts.Request.Unique, "unique", false, "Collapse repeated log lines into counted unique entries")
	cmd.Flags().BoolVar(&opts.Request.K8s, "k8s", false, "Apply Kubernetes-oriented log normalization")
	cmd.Flags().IntVar(&opts.Request.MaxInputBytes, "max-input-bytes", 0, "Limit piped stdin to this many bytes before sending it")
	cmd.Flags().IntVar(&opts.Request.MaxInputLines, "max-input-lines", 0, "Limit piped stdin to this many lines after reduction")
	cmd.Flags().IntVar(&opts.Request.MaxInputTokens, "max-input-tokens", 0, "Approximate token budget for piped stdin")
	cmd.Flags().StringVar(&opts.Request.InputReduction, "input-reduction", "", "How to handle oversized stdin for token budgeting: off, truncate, fail, or summarize")
	cmd.Flags().IntVar(&opts.Request.SummarizeChunkTokens, "summarize-chunk-tokens", 0, "Approximate token budget per chunk for multi-pass summarization")
	cmd.Flags().StringVar(&opts.Request.SummarizeIntermediateModel, "summarize-intermediate-model", "", "Model to use for intermediate summarization passes")
	cmd.Flags().IntVar(&opts.Request.HeadLines, "head-lines", 0, "Keep only the first N stdin lines")
	cmd.Flags().IntVar(&opts.Request.TailLines, "tail-lines", 0, "Keep only the last N stdin lines")
	cmd.Flags().IntVar(&opts.Request.TailLines, "tail", 0, "Alias for --tail-lines")
	cmd.Flags().IntVar(&opts.Request.SampleLines, "sample-lines", 0, "Keep a deterministic sample of N stdin lines")
	cmd.Flags().BoolVarP(&opts.Request.Shell, "shell", "s", false, "Generate a shell command")
	cmd.Flags().BoolVarP(&opts.Request.DescribeShell, "describe-shell", "d", false, "Describe a shell command")
	cmd.Flags().BoolVarP(&opts.Request.Code, "code", "c", false, "Generate only code output")
	cmd.Flags().BoolVar(&opts.Request.NoMD, "no-md", false, "Disable markdown rendering")
	cmd.Flags().StringVar(&opts.Request.Chat, "chat", "", "Named chat session")
	cmd.Flags().StringVar(&opts.Request.Repl, "repl", "", "Start an interactive REPL session")
	cmd.Flags().StringVarP(&opts.Request.Profile, "profile", "p", "", "Log analysis profile (requires --analyze-logs)")
	cmd.Flags().StringVar(&opts.Request.Role, "role", "", "Named role")
	cmd.Flags().StringVarP(&opts.Request.Template, "template", "t", "", "Named template")
	cmd.Flags().Float64Var(&opts.Request.Temperature, "temperature", 0, "Sampling temperature")
	cmd.Flags().StringVar(&opts.Request.Schema, "schema", "", "Schema DSL or JSON schema file")
	cmd.Flags().Float64Var(&opts.Request.TopP, "top-p", 1, "Top-p nucleus sampling")
	cmd.Flags().BoolVar(&opts.Request.Cache, "cache", true, "Enable disk cache")
	cmd.Flags().BoolVar(&opts.Editor, "editor", false, "Open $EDITOR to compose the prompt")
	cmd.Flags().BoolVar(&opts.Request.Interaction, "interaction", true, "Allow interactive prompts")
	cmd.Flags().BoolVar(&opts.Request.ContinueLast, "continue", false, "Continue the last chat session")
	cmd.Flags().BoolVar(&opts.Request.NoStream, "no-stream", false, "Disable streaming")
	cmd.Flags().BoolVarP(&opts.Request.Extract, "extract", "x", false, "Extract first fenced code block")
	cmd.Flags().StringVar(&opts.Request.Save, "save", "", "Save current flags as a template")
	cmd.Flags().BoolVar(&opts.Request.Log, "log", false, "Force logging for this invocation")
	cmd.Flags().BoolVarP(&opts.Request.NoLog, "no-log", "n", false, "Disable logging for this invocation")
	cmd.Flags().StringVar(&opts.Execute, "execute", "", "Execute generated shell command using host, safe, or sandbox mode")
	cmd.Flags().BoolVar(&opts.HostExec, "host", false, "Alias for --execute host")
	cmd.Flags().BoolVar(&opts.SafeExec, "safe", false, "Alias for --execute safe")
	cmd.Flags().BoolVar(&opts.SandboxExec, "sandbox", false, "Alias for --execute sandbox")
	cmd.Flags().BoolVar(&opts.Request.ForceRiskyShell, "force-risky-shell", false, "Allow high-risk host shell execution without an extra safety check")
	cmd.Flags().StringVar(&opts.Request.SandboxRuntime, "sandbox-runtime", "", "Sandbox runtime to use for shell execution: docker or podman")
	cmd.Flags().BoolVar(&opts.DockerRuntime, "docker", false, "Alias for --sandbox-runtime docker")
	cmd.Flags().BoolVar(&opts.PodmanRuntime, "podman", false, "Alias for --sandbox-runtime podman")
	cmd.Flags().StringVar(&opts.Request.SandboxImage, "sandbox-image", "", "Container image to use for sandbox shell execution")
	cmd.Flags().StringVar(&opts.Request.SandboxImage, "img", "", "Alias for --sandbox-image")
	cmd.Flags().BoolVar(&opts.Request.SandboxNetwork, "sandbox-network", false, "Allow network access in sandbox shell execution")
	cmd.Flags().BoolVar(&opts.Request.SandboxNetwork, "net", false, "Alias for --sandbox-network")
	cmd.Flags().BoolVar(&opts.Request.SandboxWrite, "sandbox-write", false, "Allow writing to the mounted workspace in sandbox shell execution")
	cmd.Flags().BoolVar(&opts.Request.SandboxWrite, "rw", false, "Alias for --sandbox-write")
}
